import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useClient, useQuery } from 'urql'
import { GET_ALL_PRODUCTS } from '../lib/query';
import { v4 as uuidv4 } from 'uuid';
import Product from '../components/Product';
import { IProduct } from '../interface';
import { useShopContext } from '../lib/context';



const Home: NextPage = () => {
  // const client = useClient();
  const { showCart } = useShopContext();
  const [{data,error,fetching}] = useQuery({
    query:GET_ALL_PRODUCTS
  });
  // const [products,setProducts] = useState<IProduct[]>([]);

  // useEffect(()=>{
  //   const getAllProducts = async() => {
  //     const res = await client.query(GET_ALL_PRODUCTS);
  //     const data = (await res.toPromise()).data.products.data
  //     setProducts(data);
  //   }
  //   getAllProducts();
  //   console.log(products)
  // },[])


  const { data:products } = data?.products || {}
  // console.log(products)
  if(fetching) return <p>Loading...</p>
  if(error) return <p>Theres an error</p>

  return (
    <div className='max-w-7xl mx-auto min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='grid grid-cols-1 md:grid-cols-3 gap-4 lg:grid-cols-4'>
        {products?.map((product:IProduct)=>(

            <Product key={uuidv4()} product={product} />
          
       
        ))}
      </section>

          
      
    </div>
  )
}

export default Home
